api:
  version: '1.5.1'

auth:
  activated: false
  validate:
    audience: 'aud-shlabadawoop'
    issuer: 'iss-shlabadawoop'
  wellKnown:
    jwksUri: 'someJwksUri'

typeorm:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'postgres'
  password: 'secret'
  database: 'stc-default'
  synchronize: true
  logging: false
  entities:
    # Add your entities
    # This is a string array, use class name as value
    - 'Series'
